INSERT INTO AUTHORITY_ENTITY VALUES(1,'ADMIN');
INSERT INTO AUTHORITY_ENTITY VALUES(2,'USER');

INSERT INTO USER_ENTITY VALUES(1,true,true,true,true,'$2a$10$Bg75l5IAH5UKTlsD06yEeeNSm4OvNQz0gii7AaKIufs64w4go92ke','SampleAdmin');
INSERT INTO USER_ENTITY VALUES(2,true,true,true,true,'$2a$10$7sU952A0bvbs/5lhAgkcgeiDQvoOFLR.0YewVtdNsyUyAfaNrw4n6','SampleUser1');
INSERT INTO USER_ENTITY VALUES(3,true,true,true,true,'$2a$10$7sU952A0bvbs/5lhAgkcgeiDQvoOFLR.0YewVtdNsyUyAfaNrw4n6','SampleUser2');

INSERT INTO USER_ENTITY_AUTHORITIES VALUES(1,1);
INSERT INTO USER_ENTITY_AUTHORITIES VALUES(2,2);
INSERT INTO USER_ENTITY_AUTHORITIES VALUES(3,2);
